### ISSUE TITLE
RTL Support?

### ISSUE THREAD

**Issue by doronyaary** [gasparesganga/jquery-message-box#12]
Hi,

First of all, thank you for this solution - its super easy and working as expected.
Is there support for RTL languages? Any CSS magic I can do here?
Its important to mention that the HTML page the dir="rtl" in it.

Cheers :-)

**Comment by gasparesganga** [comment]
Hi, thank you for your feedback!

Honestly, I have no idea nor experience at all with RTL languages... Have you tried playing around with `direction` and `text-align` CSS properties? Using `.messagebox` and `.messagebox *` selectors you should be able to catch everything related to this plugin.

If you have a working example, feel free to share it and I could try to work on it ;)

**Comment by doronyaary** [comment]
Hi,

First of all, many thank for the quick tip you provided, and you were right - it was the CSS trick. For future reference and if you would need this in the future - this did the trick perfectly:

```css
.messagebox * { direction: rtl !important; text-align: right !important; }
```


So, again thanks, I will close the issue.

Cheers :-)

**Comment by gasparesganga** [comment]
Great!!!
Thank you for leaving the reference for other users!
