### ISSUE TITLE
IE 6 is unsupported?

### ISSUE THREAD

**Issue by erhuabushuo** [gasparesganga/jquery-message-box#3]

**Comment by gasparesganga** [comment]
Yes, definitely it is not supported.
And I would ***NOT*** advice to support such an old browser anyways.

It doesn't matter if your user base may be in the 1% of population who still use it, you should encourage them to migrate to a newer and secure web browser (it's for their own good anyways).
I remember those times as a web developer being a nightmare, trying to support different versions of IE *(using multiple kludgy and mostly unknown hacks, especially CSS ones!)*.
