### ISSUE TITLE
Getting error at line 47 column 9 expected identifer, string or number

### ISSUE THREAD

**Issue by chartierpw** [gasparesganga/jquery-message-box#4]
This just started happening, no idea why.
I'm doing some data verification and if the data fails the test, I show the message box.  I get the error when I load the master page where the message box js and css is linked.  I'm using Visual Studios 2013, messagebox.js v2.2.1.

**Comment by gasparesganga** [comment]
Yep, there's a comma in excess and VS2013 probably complains about it.
I'll release a fix tomorrow, don't worry

**Comment by chartierpw** [comment]
Sir,

I now get a different error, same environment:

JavaScript critical error at line 128, column 13 in 
http://localhost:4101/javascripts/messagebox.js\n\nSCRIPT1028: Expected 
identifier, string or number

R/
Prescott ...
-----Original Message-----

**Comment by gasparesganga** [comment]
You have already opened another issue #5 , it's not necessary to write the same here
