### ISSUE TITLE
JavaScript critical error at line 128, column 13

### ISSUE THREAD

**Issue by chartierpw** [gasparesganga/jquery-message-box#5]
I now get a different error, same environment:

JavaScript critical error at line 128, column 13 in http://localhost:4101/javascripts/messagebox.js\n\nSCRIPT1028: Expected identifier, string or number

**Comment by gasparesganga** [comment]
This sounds really *Internet Explore-ish*...
This issue there is that `class` is a reserved word and cannot be used without quotes in an object literal. Of course it's just some Microsoft super special behaviour, but I'll fix that one too.

**Comment by chartierpw** [comment]
Yes, Internet Explorer .... I'm testing an process recently integrated into 
our product,.  I always test with IE first as this is the most problematic 
browser.  I personally use Firefox, IE is a piece of garbage  as far as I'm 
concerned, but a lot of our clients use IE.

R/
Prescott ...
-----Original Message-----

**Comment by gasparesganga** [comment]
You should have your users upgrade to a modern browser. There's not a single reasonable reason to keep using IE today. Anyways, I'm deploying this fix.
I'm doing this because those changes are not a big deal in the code, but I will **not** make any major change in order to support obsolete browsers, I'm sorry.

**Comment by chartierpw** [comment]
Unfortunately we have no control over what browser people use, we have to 
support all browsers as our product is used by the general public at large.  
We have to support IE > v9, not an easy task but necessary.

R/
Prescott ...
-----Original Message-----

**Comment by chartierpw** [comment]
That did the trick, thank you for doing this.  I certainly can understand 
your issues with IE, I definitely share them, I just don't have any choice.

What also would be useful for me with this library is a positioning and size 
option.  I have a lot of css and yours and mine are conflicting and I had to 
change yours from 90% to 30% as the box width was taking up 90% of the 
window and is displaying on the left edge, even 30% is a little too wide for 
my liking.  I can "fix" that, but I really don't want to modify code that 
isn't mine.  I also had a conflict with a window resize function in another 
javascript, I just deleted mine and that solved my issue as long as it 
doesn't impact anything else on the page, i'm ok with that "fix", remains to 
be seen though.

If you this IE is bad, you should see the issues I'm having with Windows 10 
and Edge ..... O.M.G .....

In any event, it would be nice to have ....
Thanks again ...

R/
Prescott ....
-----Original Message-----

**Comment by gasparesganga** [comment]
There are positioning and size options actually, in the form of [top](https://gasparesganga.com/labs/jquery-message-box/#top) and [width](https://gasparesganga.com/labs/jquery-message-box/#width) options.

The default CSS provided in the file `messagebox.css` is intended just as a default style, it is supposed to be changed accorging to your likings, preferably ovverriding it with another CSS file.

Or did you mean something else?

**Comment by chartierpw** [comment]
Yest I was thinking of a specific option on where to display the message 
box, for example:

This is the ShowMessage function I'm using now:

function ShowMessage(mymessage) {
            $.MessageBox({
                buttonDone: "OK",
                message: mymessage
            });
        }

This is what would be nice to have:

function ShowMessage(mymessage) {
            $.MessageBox({
                buttonDone: "OK",
Position: topleft or topright or center(also middle), or middleright or 
middleleft, or bottomleft, bottomright, bottommiddle, or whatever you think 
works best.,
size: (can be expressed in percentage or px),
titlebarbackgroundcolor: somevalue,
messageareabackgroundcolor: somevalue, 
                message: mymessage
            });
        }
I had looked through all the options and I like what I see, I just didn't 
see anything specifically related to size, position and color(s).  Yes I can 
modify the css to do what I want, just a suggestion for future release ....

R/
Prescott ...
-----Original Message-----

**Comment by gasparesganga** [comment]
Everything you have in mind can be accomplished with current setup.
Use `top` option for positioning and `width` option for *size*, as written in the documentation: *you can specify an amount in pixels or any other CSS-compatible unit (Es. "80%")*.

About colors and background, the appropriate place for that is into your CSS. You can either override the default classes or use your own classes. The `customClass` general option and specific `class` options for buttons are designed just for that.

Please **read carefully the documentation**, there is even a dedicated [example](https://gasparesganga.com/labs/jquery-message-box/#example-7---customize-it).
