### ISSUE TITLE
[Feature request] Add TextArea as a new input option

### ISSUE THREAD

**Issue by A-Matt** [gasparesganga/jquery-message-box#6]
I've successfully been able to modify the file myself to allow for textarea using a JQuery Element of a `textarea`, however the [line 494](https://github.com/gasparesganga/jquery-message-box/blob/v3.0.0/src/messagebox.js#L494) needs an edit to also get the values from it.

I'm not wizard at doing pull requests on GitHub nor if you would like to full implement it into a feature directly put into the program... But I though this might be a good feature request to allow for TextArea input rather than a select / input.

**Comment by gasparesganga** [comment]
it would be a nice feature indeed.
Right now I forget whether there was any issue of any kind which kept me from adding it before.
I'll look into it and release a new minor version that includes it.
Thank you

**Comment by gasparesganga** [comment]
Here you go, v3.1.0 just released.
Thank you for the idea :)
